spring:
  datasource:
    url: jdbc:mysql://rm-8vbzbcg67j8o4e92q58870.mysql.zhangbei.rds.aliyuncs.com:3306/jpa_demo?${my.datasource.settings}
    username: jpa_demo
    password: ZAQ!2wsx
cao-mu:
  token-expires-time: P7D
  token-exclude-url: /noLogin